# Generated by Django 4.1.5 on 2023-01-25 01:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memo', models.CharField(max_length=120)),
            ],
        ),
    ]
